server:
  port: 8080
spring:
  application:
    name: reggie_take_out
# 单数据库配置
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.24.129:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: MySQL5.7

# 以下为MySQL读写分离
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.24.129:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: MySQL5.7
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.24.130:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: MySQL5.7
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true
# 以上为MySQL读写分离

# redis缓存数据
  redis:
    host: 192.168.24.129
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 512
        max-idle: 256
        min-idle: 256
        max-wait: -1
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间（ms）

  # mongodb存储订单信息
  data:
    mongodb:
      # 主机地址
      host: 192.168.24.129
      # 数据库
      database: reggiedb
      # 默认端口是27017
      port: 27017
      # 也可以使用uri连接
      # uri: mongodb://192.168.40.134:27017/articledb

  # kafka接受和发送订单消息
  kafka:
    bootstrap-servers: 192.168.24.129:9002
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 500
    listener:
      ack-mode: MANUAL_IMMEDIATE


# MybatisPlus
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 自定义参数
custom-parameters:
  # 图片相关参数
  path:
    # 图片保存路径
    enable-linux: false
    # centos保存路径
    save-image-path-linux: /usr/local/reggie/upload/
    # windows保存路径
    save-image-path-windows: D:\Java\项目\瑞吉外卖\myCode\upload\

  # 短信验证码
  send-msg:
    # 是否启用短信发送验证码
    enable: true
    # 腾讯云账户密钥对Id
    secret-id: AKIDX0V3SjmbGwdM1c8whMxRTXaVHqFYikeL
    # 腾讯云账户密钥对Key
    secret-key: c5OfwFZoHZlssjZJxhIgu7Nf2SsLuMn6
    # SDK默认超时时间
    conn-timeout: 5
    # 短信应用ID
    sdk-app-id: 1400677800
    # 短信签名
    sign-name: 蛋蛋编程
    # 模板ID
    template-id: 1401840
    # 消息头
    msg-head: 【瑞吉外卖】

  # cookie
  cookie:
    enable: true