server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.24.129:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: MySQL5.7
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:\Java\项目\瑞吉外卖\myCode\reggie_take_out\upload\

sendMsg:
  secretId: AKIDX0V3SjmbGwdM1c8whMxRTXaVHqFYikeL
  secretKey: c5OfwFZoHZlssjZJxhIgu7Nf2SsLuMn6
  connTimeout: 5
  sdkAppId: 1400677800
  signName: 蛋蛋编程
  # templateId: 1401550
  templateId: 1401840
  msgHead: 【瑞吉外卖】